### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by Fakepanda99** [binxi0629/C2DBbandstructures#1]
hello, my friend. 
I want to know how can I download the database named C2DB. I try my best to download it from the website of C2DB, but I can not find the download link. 
thank you very much. :)

**Comment by binxi0629** [comment]
Hello,
For the database, you need to contact the author Kristian S. Thygesen and he may send it to you. You can find his email address in his paper. Here's a link (https://cmr.fysik.dtu.dk/c2db/c2db.html#c2db) FYI.

**Comment by binxi0629** [comment]
> hello, my friend. I want to know how can I download the database named C2DB. I try my best to download it from the website of C2DB, but I can not find the download link. thank you very much. :)

Hello,
For the database, you need to contact the author Kristian S. Thygesen and he may send it to you. You can find his email address in his paper. Here's a link (https://cmr.fysik.dtu.dk/c2db/c2db.html#c2db) FYI.

**Comment by Fakepanda99** [comment]
> > hello, my friend. I want to know how can I download the database named C2DB. I try my best to download it from the website of C2DB, but I can not find the download link. thank you very much. :)
> 
> Hello, For the database, you need to contact the author Kristian S. Thygesen and he may send it to you. You can find his email address in his paper. Here's a link (https://cmr.fysik.dtu.dk/c2db/c2db.html#c2db) FYI.

Thanks,
I have sent the email to Dr.Thygesen, But he do not reply. I am waiting hard. T-T..
